export * from "./addressDetails";
export * from "./_projectDetails";
export * from "./businessDetails";
export * from "./collateralDetails";
export * from "./financialRatios";
export * from "./generalDetails";
export * from "./incomeDetails";
export * from "./managementDetails";
export * from "./promoterDetails";
