export const leadGridMetaData = {
  gridConfig: {
    dense: false,
    pageSize: [5, 10, 20],
    defaultPageSize: "5",
    gridLabel: "Leads",
    rowIdColumn: "tran_cd",
  },
  columns: [
    {
      accessor: "tran_cd",
      columnName: "Lead CD",
      sequence: 1,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "inquiry_tran_cd",
      columnName: "Inquiry CD",
      sequence: 2,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "active_flag",
      columnName: "Active",
      sequence: 5,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "inactive_reason_cd",
      columnName: "Inactive Reason",
      sequence: 6,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "priority",
      columnName: "Priority",
      sequence: 7,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "source_cd",
      columnName: "Source",
      sequence: 8,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "remarks",
      columnName: "Remarks",
      sequence: 9,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "assigned_id",
      columnName: "Assign ID",
      sequence: 10,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "team_lead_id",
      columnName: "Team Lead ID",
      sequence: 11,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "lead_entered_date",
      columnName: "Lead Entered Date",
      sequence: 15,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "generation_dt",
      columnName: "Generate Dt",
      sequence: 17,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "category_id",
      columnName: "Category",
      sequence: 1.1,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "product_cd",
      columnName: "Product CD",
      sequence: 1.2,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "sub_product1",
      columnName: "Sub Product-1",
      sequence: 1.3,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "sub_product2",
      columnName: "Sub Product-2",
      sequence: 1.4,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "empl_cd",
      columnName: "Employee Type",
      sequence: 23,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "first_name",
      columnName: "First Name",
      sequence: 1.5,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "middle_name",
      columnName: "Middle Name",
      sequence: 1.6,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "last_name",
      columnName: "Last Name",
      sequence: 1.7,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "gender",
      columnName: "Gender",
      sequence: 1.8,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "mobile",
      columnName: "Moibile",
      sequence: 1.9,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
    {
      accessor: "e_mail_id",
      columnName: "Email ID",
      sequence: 2,
      width: 150,
      minWidth: 100,
      maxWidth: 200,
      alignment: "right",
      componentType: "default",
      disableSortBy: false,
      disableFilters: false,
      filterComponentType: "valueFilter",
      isVisible: true,
    },
  ],
};
