export const worklogGridMetaData = {
  gridConfig: {
    dense: false,
    pageSize: [20, 30, 50],
    defaultPageSize: "20",
    gridLabel: "Todays Worklog",
    rowIdColumn: "tran_cd",
    allowGlobalFilter: true,
    allowColumnReordering: true,
    allowColumnHiding: true,
    allowKeyboardNavigation: true,
  },
  columns: [
    {
      columnName: "Serial No",
      componentType: "default",
      accessor: "tran_cd",
      sequence: 0,
      alignment: "left",
      disableSortBy: false,
    },
    {
      columnName: "Tran Date",
      componentType: "date",
      accessor: "tran_date",
      sequence: 1,
      alignment: "center",
      dateFormat: "dd/MM/yyyy",
      disableSortBy: false,
      filterComponentType: "rangeFilter",
      filterProps: {
        type: "date",
      },
    },
    {
      columnName: "Type",
      componentType: "default",
      accessor: "type",
      sequence: 2,
      alignment: "left",
    },
    {
      columnName: "Billable",
      componentType: "default",
      accessor: "billable",
      sequence: 3,
      alignment: "left",
    },
    {
      columnName: "Description",
      componentType: "default",
      accessor: "description",
      sequence: 4,
      alignment: "left",
    },
    {
      columnName: "Start Time",
      componentType: "date",
      accessor: "start_time",
      sequence: 5,
      alignment: "center",
      dateFormat: "hh:mm aa",
    },
    {
      columnName: "End Time",
      componentType: "date",
      accessor: "end_time",
      sequence: 6,
      alignment: "center",
      dateFormat: "hh:mm aa",
    },
  ],
};
