export const taskAssignMetadata = {
  form: {
    name: "assignTaskFormMetadata",
    label: "Task Assign",
    resetFieldOnUmnount: false,
    validationRun: "onBlur",
    submitAction: "home",
    render: {
      ordering: "auto",
      renderType: "simple",
      gridConfig: {
        item: { xs: 12, sm: 4, md: 4 },
        container: { direction: "row", spacing: 2 },
      },
    },
    componentProps: {
      textField: { fullWidth: true },
      select: { fullWidth: true },
      datePicker: { fullWidth: true },
      numberFormat: { fullWidth: true },
      inputMask: { fullWidth: true },
    },
  },
  fields: [
    {
      render: { componentType: "textField" },
      name: "subject",
      label: "Task Subject",
      placeholder: "Task Subject",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField" },
      name: "type",
      label: "Type of Task",
      placeholder: "Type of Task",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField" },
      name: "othersType",
      label: "Other Type of Task",
      placeholder: "Other Type of Task",
      options: "getRetailEmployee",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField" },
      name: "status",
      label: "Status of Task",
      placeholder: "Status of Task",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "datePicker" },
      name: "dueDate",
      label: "Task Due Date",
      format: "dd/MM/yyyy",
      placeholder: "DD/MM/YYYY",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "datePicker" },
      name: "completionDate",
      label: "Task Completion Date",
      placeholder: "DD/MM/YYYY",
      format: "dd/MM/yyyy",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField" },
      name: "description",
      label: "Description about task",
      placeholder: "Description about task",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField" },
      name: "enteredBy",
      label: "Task Assign by",
      placeholder: "Task Assign by",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "datePicker" },
      name: "enteredDate",
      label: "Task Created On",
      placeholder: "DD/MM/YYYY",
      format: "dd/MM/yyyy",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField" },
      name: "modifiedBy",
      label: "Task Modified by",
      placeholder: "Task Modified by",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "datePicker" },
      name: "modifiedDate",
      label: "Task Modified Date",
      placeholder: "DD/MM/YYYY",
      format: "dd/MM/yyyy",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
    {
      render: { componentType: "textField" },
      name: "taskSource",
      label: "Source of Task",
      placeholder: "Source of Task",
      GridProps: { xs: 12, md: 3, sm: 3 },
    },
  ],
};
