export const coldCallingMetaData = {
  gridConfig: {
    dense: false,
    pageSize: [20, 30, 50],
    defaultPageSize: "20",
    gridLabel: "Cold Calling",
    rowIdColumn: "tran_cd",
    allowColumnReordering: true,
    allowColumnHiding: true,
    allowKeyboardNavigation: true,
    allowGlobalFilter: true,
  },
  columns: [
    {
      accessor: "firstName",
      columnName: "First Name",
      sequence: 1,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "middleName",
      columnName: "Middle Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "lastName",
      columnName: "Last Name",
      sequence: 3,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "gender",
      columnName: "Gender",
      sequence: 4,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "mobile",
      columnName: "Mobile",
      sequence: 5,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "email",
      columnName: "Email ID",
      sequence: 6,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "remarks",
      columnName: "Remarks",
      sequence: 8,
      alignment: "left",
      componentType: "default",
    },
  ],
};
