export const MonthlyTargetGridMetadata = {
  columns: [
    {
      columnName: "Line No",
      componentType: "default",
      accessor: "lineNo",
      sequence: 1,
      alignment: "left",
    },
    {
      columnName: "Target Month",
      componentType: "default",
      accessor: "targetMonth",
      sequence: 2,
      alignment: "left",
    },
    {
      columnName: "Partner Volume",
      componentType: "default",
      accessor: "partnerVolume",
      sequence: 3,
      alignment: "left",
    },
    {
      columnName: "Retail Volume",
      componentType: "default",
      accessor: "retailsVolume",
      sequence: 4,
      alignment: "left",
    },
    {
      columnName: "SME Volume",
      componentType: "default",
      accessor: "smeVolume",
      sequence: 5,
      alignment: "left",
    },
    {
      columnName: "Infra Volume",
      componentType: "default",
      accessor: "infraVolume",
      sequence: 6,
      alignment: "left",
    },
    {
      columnName: "Unsecured Volume",
      componentType: "default",
      accessor: "unsecuredVolume",
      sequence: 7,
      alignment: "left",
    },
    {
      columnName: "Insurance Volume",
      componentType: "default",
      accessor: "insuranceVolume",
      sequence: 8,
      alignment: "left",
    },
    {
      columnName: "Total Volume",
      componentType: "default",
      accessor: "totalVolume",
      sequence: 9,
      alignment: "left",
    },
    {
      columnName: "Remarks",
      componentType: "default",
      accessor: "remarks",
      sequence: 10,
      alignment: "left",
    },
  ],
  gridConfig: {
    dense: true,
    gridLabel: "Monthly Target",
    rowIdColumn: "lineNo",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableGroupBy: true,
    disableSorting: true,
    hideHeader: false,
    containerHeight: {
      min: "40vh",
      max: "50vh",
    },
  },
};
