import { GridMetaDataType } from "components/dataTableStatic";

const metaData: GridMetaDataType = {
  columns: [
    {
      columnName: "Name of Bank",
      componentType: "editableSelect",
      accessor: "bankName",
      sequence: 0,
      alignment: "left",
      isVisible: false,
      options: "getPerfiosBankList",
    },
    {
      columnName: "Branch Name",
      componentType: "editableSelect",
      accessor: "branchName",
      sequence: 1,
      alignment: "left",
      isVisible: false,
      options: "getPerfiosBankList",
    },
    {
      columnName: "Name of Department",
      componentType: "editableTextField",
      accessor: "departmentName",
      sequence: 2,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Product Name",
      componentType: "editableTextField",
      accessor: "productName",
      sequence: 3,
      alignment: "left",
      isVisible: false,
    },

    {
      columnName: "Vintage of Business",
      componentType: "editableTextField",
      accessor: "businessVintage",
      sequence: 4,
      alignment: "left",
      isVisible: false,
    },

    {
      columnName: "Age of main Promoters",
      componentType: "editableTextField",
      accessor: "propmoterAge",
      sequence: 5,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "T/O LB",
      componentType: "editableTextField",
      accessor: "toLB",
      sequence: 6,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "T/O UB",
      componentType: "editableTextField",
      accessor: "toUB",
      sequence: 7,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Loan LB",
      componentType: "editableTextField",
      accessor: "loanLB",
      sequence: 8,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Loan UB",
      componentType: "editableTextField",
      accessor: "loanUB",
      sequence: 9,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Collateral Coverage",
      componentType: "editableTextField",
      accessor: "collateralCoverage",
      sequence: 10,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Type of Collateral",
      componentType: "editableTextField",
      accessor: "collateralType",
      sequence: 11,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "ROI LB",
      componentType: "editableTextField",
      accessor: "roiLB",
      sequence: 12,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "ROI UB",
      componentType: "editableTextField",
      accessor: "roiUB",
      sequence: 13,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Minimum CIBIL Score of Promoters",
      componentType: "editableTextField",
      accessor: "promoterCibilScore",
      sequence: 14,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "CMR of the Company",
      componentType: "editableTextField",
      accessor: "companyCMR",
      sequence: 15,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "EBIDTA Amount As per Audited Financials",
      componentType: "currency",
      accessor: "financilaAuditEBIDTAAmount",
      sequence: 16,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Current Ratio",
      componentType: "currency",
      accessor: "curretnRatio",
      sequence: 17,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "DSCR As per Audited Financials",
      componentType: "editableTextField",
      accessor: "financilaAuditDSCR",
      sequence: 18,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "% Of Cheque Bounces allowed",
      componentType: "editableTextField",
      accessor: "chequeBouncePer",
      sequence: 19,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Processing Fees",
      componentType: "editableTextField",
      accessor: "processingFees",
      sequence: 20,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "External Rating Required & Support",
      componentType: "editableTextField",
      accessor: "externalRating",
      sequence: 21,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Industry Focus",
      componentType: "editableTextField",
      accessor: "industryFocus",
      sequence: 22,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "whether We have Payout?",
      componentType: "editableTextField",
      accessor: "payout",
      sequence: 23,
      alignment: "left",
      isVisible: false,
    },
    {
      columnName: "Rate of Payout",
      componentType: "editableTextField",
      accessor: "payoutRate",
      sequence: 24,
      alignment: "left",
      isVisible: false,
    },
  ],

  gridConfig: {
    dense: true,
    gridLabel: "Bank Master",
    rowIdColumn: "id",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: true,
    disableGroupBy: true,
    disableSorting: true,
    hideHeader: true,
    containerHeight: {
      min: "40vh",
      max: "50vh",
    },
  },
};

export default metaData;
