export const coldCallingMetaData = {
  gridConfig: {
    dense: false,
    pageSize: [20, 30, 50],
    defaultPageSize: "20",
    gridLabel: "Cold Calling",
    rowIdColumn: "tran_cd",
    allowColumnReordering: true,
    allowColumnHiding: true,
    allowKeyboardNavigation: true,
    allowGlobalFilter: true,
  },
  columns: [
    {
      accessor: "salutation",
      columnName: "Salutation",
      sequence: 1,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "full_name",
      columnName: "Full Name",
      sequence: 2,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "mobile",
      columnName: "Mobile",
      sequence: 3,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "email_id",
      columnName: "Email ID",
      sequence: 4,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "category_id",
      columnName: "Product Category",
      sequence: 5,
      alignment: "left",
      componentType: "default",
    },
    {
      accessor: "loan_amt",
      columnName: "Loan Amount",
      sequence: 6,
      alignment: "left",
      componentType: "currency",
    },
    {
      accessor: "status",
      columnName: "Status",
      sequence: 7,
      alignment: "left",
      componentType: "default",
    },
  ],
};
