import { GridMetaDataType } from "components/dataTableStatic";

export const CompanyListGrid: GridMetaDataType = {
  gridConfig: {
    dense: true,
    gridLabel: "Companies Search Result",
    rowIdColumn: "cin",
    defaultColumnConfig: {
      width: 150,
      maxWidth: 250,
      minWidth: 100,
    },
    allowColumnReordering: false,
    disableSorting: false,
    disableGroupBy: true,
    allowRowSelection: false,
    disableGlobalFilter: true,

    containerHeight: {
      min: "40vh",
      max: "50vh",
    },
  },
  columns: [
    {
      columnName: "Action",
      componentType: "action",
      accessor: "action",
      sequence: 0,
      alignment: "left",
      actions: ["proceed"],
      width: 100,
      minWidth: 100,
      maxWidth: 100,
    },
    {
      columnName: "ID",
      componentType: "default",
      accessor: "company-id",
      sequence: 0,
      alignment: "left",
      width: 130,
      minWidth: 130,
      maxWidth: 130,
    },
    {
      columnName: "Name",
      componentType: "default",
      accessor: "company-name",
      sequence: 1,
      alignment: "left",
      width: 250,
      maxWidth: 400,
    },
    {
      columnName: "CIN",
      componentType: "default",
      accessor: "cin",
      sequence: 2,
      alignment: "left",
      width: 200,
      maxWidth: 250,
      minWidth: 100,
    },
    {
      columnName: "City",
      componentType: "default",
      accessor: "city",
      sequence: 3,
      alignment: "left",
    },
    {
      columnName: "State",
      componentType: "default",
      accessor: "state",
      sequence: 4,
      alignment: "left",
    },
    {
      columnName: "Status",
      componentType: "default",
      accessor: "company-status",
      sequence: 5,
      alignment: "left",
    },
    {
      columnName: "Last Refreshed On",
      componentType: "date",
      accessor: "last-refresh-time",
      sequence: 6,
      alignment: "left",
      width: 190,
      maxWidth: 250,
      minWidth: 100,
    },
  ],
};
